export const skills = [
  { name: 'JavaScript' },
  { name: 'HTML/CSS' },
  { name: 'React' },
  { name: 'Node.js' },
  { name: 'Express' },
  { name: 'Next.js' },
  { name: 'Gatsby' },
  { name: 'GraphQL' },
  { name: 'TypeScript' },
  { name: 'PostgreSQL' },
  { name: 'Git' },
  { name: 'GitHub' },
  { name: 'GitLab' },
  { name: 'Firebase' },
  { name: 'Redux' },
  { name: 'Vue' },
  { name: 'Angular 6' },
  { name: 'Typescript' },
  { name: 'Python' },
  { name: 'Django' },
  { name: 'MongoDB' },
  { name: 'Ruby on Rails' },
  { name: 'Amazon web services' },
  { name: 'SQL' },
  { name: 'C#' },
  { name: 'Unity3d' },
  { name: 'Unity for game development' },
  { name: 'C++' },
  { name: 'Unreal engine 4' },
  { name: 'Game development' },
  { name: 'Objective-C' },
  { name: 'Swift' },
  { name: 'Foundation' },
  { name: 'Cocoa' },
  { name: 'SwiftUI' },
  { name: 'Osx' },
  { name: 'Mac os x' },
  { name: 'Android' },
  { name: 'Dart/flutter' },
  { name: 'Flutter' },
  { name: 'Java' },
  { name: 'Kotlin' },
  { name: 'React native' },
  { name: 'iOS' },
  { name: 'Go' },
  { name: 'Test automation' },
  { name: 'Selenium webdriver' },
  { name: 'Quality assurance' },
  { name: 'Manual testing' },
  { name: 'Security' },
  { name: 'Security testing' },
  { name: 'Information security' },
  { name: 'Network security' },
  { name: 'Sap security' },
  { name: 'Spring boot' },
  { name: 'PHP' },
  { name: 'Blockchain' },
  { name: 'Ethereum' },
  { name: 'Smartcontracts' },
  { name: 'Hyperledger fabric' },
  { name: 'Solidity' },
  { name: 'Cryptocurrency' },
  { name: 'Crypto' },
  { name: 'WordPress' },
  { name: 'Joomla' },
  { name: 'Shopify' },
  { name: 'Drupal' },
  { name: 'Microsoft excel' },
  { name: 'Microsoft power bi' },
  { name: 'Data analytics' },
  { name: 'R' },
  { name: 'Tableau' },
  { name: 'Google cloud platform' },
  { name: 'Power bi' },
  { name: 'Data warehousing' },
  { name: 'Web scraping' },
  { name: 'Azure devops' },
  { name: 'Data Modelling' },
  { name: 'Apache kafka' },
  { name: 'Machine learning' },
  { name: 'Data science' },
  { name: 'Computer vision' },
  { name: 'Artificial intelligence' },
  { name: 'Tensorflow' },
  { name: 'Natural language processing' },
  { name: 'Kubernetes' },
  { name: 'Jenkins' },
  { name: 'Docker' },
  { name: 'Ansible' },
  { name: 'Linux' },
  { name: 'Continuous integration' },
  { name: 'Terraform' },
  { name: 'ASP.NET' },
  { name: 'Visual Basic' },
  { name: 'Wpf' },
  { name: 'Xamarin' },
  { name: 'Software architecture' },
  { name: 'Database design' },
  { name: 'Application architecture' },
  { name: 'Systems architecture' },
  { name: 'Consulting' },
  { name: 'j2ee' },
  { name: 'Ionic' },
  { name: 'Mobile' },
  { name: 'Pwa' },
  { name: 'PhoneGap' },
  { name: 'jQuery Mobile' },
  { name: 'Hardware' },
  { name: 'Testing' },
  { name: 'Network' },
  { name: 'Windows application' },
  { name: 'Access' },
  { name: 'Mail' },
  { name: 'Reporting' },
  { name: 'Sharepoint' },
  { name: 'TailwindCss' },
  { name: 'Next.js' },
  { name: 'Nuxt.js' },
  { name: 'Svelte' },
  { name: 'SvelteKit' },
  { name: 'Sapper' },
  { name: 'Jira' },
  { name: 'Confluence' },
  { name: 'Atlassian' },
  { name: 'Agile' },
  { name: 'Scrum' },
]
